
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_ERROR = "GET_USERS_ERROR"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const ISFETCHING = "ISFETCHING"

